version: "3.9"

services:
  chatbot-backend:
    build: .
    container_name: chatbot
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    volumes:
      - "${PUBLIC_FOLDER}:/app/${PUBLIC_FOLDER}"
    env_file:
      - .env
    restart: unless-stopped
